const ProductPage: React.FC = () => {
  return (
    <>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
      <div>ProductPage</div>
    </>
  );
};
export default ProductPage;
